name: Github Action Demo
on: [ psuh ]
jobs: 
  Explore-GitHub-Actions:
    runs-on: ubutu-latest
    steps:
      -run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      -run: python main.py
