name: Github Action Demo
on: [ psuh ]
jobs: 
  Test:
    runs-on: [ ubutu-latest,windons-latest, mac]
    steps:
      -uses: actions/checkout@v2
      -run: echo " The job was automatically triggered by a ${{ github.event_name }} event."
      -run: python main.py
